# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += Fixer \
           ConsoleFixer \
           QtFixer

TEMPLATE = subdirs
CONFIG += warn_on \
qt \
thread

mac:LIBS +=-dead_strip
