# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += Fixer \
           ConsoleFixer \
           QtFixer

TEMPLATE = subdirs
CONFIG += warn_on \
qt \
thread

mac {
	QMAKE_MAC_SDK=/Developer/SDKs/MacOSX10.4u.sdk
	QMAKE_MACOSX_DEPLOYMENT_TARGET=10.3
        CONFIG += x86 ppc

	LIBS +=-dead_strip
}
