# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./ConsoleFixer
# Target is an application:  VbrfixConsole

POST_TARGETDEPS += ../Fixer/lib/libFixer.a 
LIBS += ../Fixer/lib/libFixer.a
INCLUDEPATH += ../Fixer 
TARGET = VbrfixConsole 
CONFIG += warn_on \
          stl \
          console 
TEMPLATE = app 
HEADERS += ConsoleFixer.h 
SOURCES += ConsoleFixer.cpp \
           main.cpp 
